kind: Deployment
apiVersion: apps/v1
metadata:
  name: warp-engine-c2-deployment
  labels:
    app: warp-engine-c2
spec:
  selector:
    matchLabels:
      app: warp-engine-c2
  replicas: 1
  template:
    metadata:
      labels:
        app: warp-engine-c2
        version: v1
    spec:
      containers:
        - name: warp-engine-c2
          image: "${helidonC2ImageBaseUrl}:${buildId}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret
      nodeSelector:
        component: c2
---
kind: Service
apiVersion: v1
metadata:
  name: warp-engine-c2-service
spec:
  type: ClusterIP
  selector:
    app: warp-engine-c2
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warp-engine-c2-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ${urlHelidonC2}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: warp-engine-c2-service
                port:
                  number: 8080