kind: Deployment
apiVersion: apps/v1
metadata:
  name: warp-engine-graal-deployment
  labels:
    app: warp-engine-graal
spec:
  selector:
    matchLabels:
      app: warp-engine-graal
  replicas: 1
  template:
    metadata:
      labels:
        app: warp-engine-graal
        version: v1
    spec:
      containers:
        - name: warp-engine-graal
          image: "${helidonGraalImageBaseUrl}:${buildId}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: ${helidonGraalNodeLabel}
---
kind: Service
apiVersion: v1
metadata:
  name: warp-engine-graal-service
spec:
  type: ClusterIP
  selector:
    app: warp-engine-graal
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warp-engine-graal-ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ${urlHelidonGraal}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: warp-engine-graal-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warp-engine-graal-ingress-path
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /warp-engine-graal(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: warp-engine-graal-service
                port:
                  number: 8080