kind: Deployment
apiVersion: apps/v1
metadata:
  name: helm-ui-deployment
  labels:
    app: helm-ui
spec:
  selector:
    matchLabels:
      app: helm-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: helm-ui
        version: v1
    spec:
      containers:
        - name: helm-ui
          image: "${helmImageBaseUrl}:${buildId}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL_GRAAL
              value: ${urlHelidonGraal}
            - name: REACT_APP_API_URL_C2
              value: ${urlHelidonC2}
            - name: REACT_APP_API_URL_NATIVE
              value: ${urlMicronautNative}
      imagePullSecrets:
        - name: ocirsecret
---
kind: Service
apiVersion: v1
metadata:
  name: helm-ui-service
spec:
  type: ClusterIP
  selector:
    app: helm-ui
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-ui-ingress-path
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /helm-ui(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: helm-ui-service
                port:
                  number: 80